name: Github Actions Demo
on: [push]
jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "ğŸ This job's status is ${{ job.status }}."
      - name: Get Docker info
        run: docker info
      - name: List docker images
        run: docker images
      - name: Build Docker stack
        run: docker compose build
      - name: List docker images
        run: docker images
      - name: Save Docker image
        run: docker save -o ${{ github.workspace }}/potluck_web.tar potluck_web
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Upload Docker image to artifact storage
        uses: actions/upload-artifact@v2
        with:
          name: docker-image
          path: ${{ github.workspace }}/potluck_web.tar

  load-docker-image:
    runs-on: ubuntu-latest
    needs: build-docker-image
    steps:
      - run: echo "ğŸ‘‹ Hello from the second job."
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Download Docker image from artifact storage
        uses: actions/download-artifact@v2
        with:
          name: docker-image
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: List docker images
        run: docker images
      - name: Load Docker image
        run: docker load -i ${{ github.workspace }}/potluck_web.tar
      - name: List docker images
        run: docker images
      - name: Start the Docker stack
        run: docker-compose up --no-build --detach
      - name: Stop the Docker stack
        run: docker-compose stop
